### ISSUE TITLE
 How do I get styles to work?

### ISSUE THREAD

**Issue by Guigui220D** [xyaman/mibu#5]
Hey! Colors work fine, but I can't get styles to work (bold, dim, etc) I always get some junk characters instead

I'm on linux and I use `try mibu.style.bold(writer)`

Thanks a lot!

**Comment by xyaman** [comment]
What terminal are you using? 
It works for me, try printing bold text and normal text and compare. Sometimes depending on the font, the change is not very noticeable.

**Comment by Guigui220D** [comment]
I get the same thing in gnome-terminal, the terminal in vscode and xterm. I don't think It's a font problem because I see "22" being printed and other stuff

**Comment by xyaman** [comment]
Sorry, I found the problem.
I don't have the time right now, but it will be fixed today. 

In the meantime, you can use `mibu.style.print.bold`.

**Comment by Guigui220D** [comment]
Indeed now it works, thanks ^^
